name: Release osxcross

on:
  workflow_dispatch:

jobs:
  package_sdks:
    uses: ./.github/workflows/sdk.yml

  collect_sdks:
    name: Collect SDKs
    runs-on: ubuntu-latest
    needs: package_sdks
    outputs:
      RELEASE_VERSION: ${{ steps.get_release_version.outputs.RELEASE_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Release Version
        id: get_release_version
        run: |
          echo "RELEASE_VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

  build_osxcross:
    name: Build osxcross
    strategy:
      fail-fast: false
      matrix:
        sdk_versions: ${{ fromJSON(needs.package_sdks.outputs.SDK_VERSIONS) }}
        ubuntu_version:
          - 18.04
          - 20.04
          - 22.04
          - 24.04
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    needs:
      - package_sdks
      - collect_sdks
    steps:
      - uses: actions/checkout@v4

      - name: Download SDK
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.sdk_versions }}
          path: tarballs

      - name: Build osxcross
        uses: uraimo/run-on-arch-action@v2
        id: build
        with:
          arch: none
          distro: none
          base_image: amd64/ubuntu:${{ matrix.ubuntu_version }}
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${PWD}:/osxcross"
          shell: /bin/bash
          install: |
            apt-get update && apt-get install -y \
              curl \
              clang \
              make \
              cmake \
              git \
              patch \
              python3 \
              libssl-dev \
              lzma-dev \
              libxml2-dev \
              xz-utils \
              bzip2 \
              cpio \
              zlib1g-dev \
              llvm-dev \
              uuid-dev
            wget https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz
            mkdir -p /llvm
            tar -xf clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz -C /llvm --strip-components=1
            rm -rf clang*.tar.xz
            wget http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.4-2_amd64.deb && sudo dpkg -i libtinfo5_6.4-2_amd64.deb
          run: |
            export PATH=/llvm/bin:$PATH
            cd /osxcross
            ls tarballs
            UNATTENDED=1 SDK_VERSION="$(echo ${{ matrix.sdk_versions }} | sed 's/-/./g')" JOBS=$(nproc) bash build.sh
            mkdir -p dist
            tar -zcf dist/osxcross-${{ matrix.sdk_versions }}-linux-amd64-gnu-ubuntu-${{ matrix.ubuntu_version }}.tar.gz -C target .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.collect_sdks.outputs.RELEASE_VERSION }}
          draft: false
          prerelease: false
          append_body: false
          fail_on_unmatched_files: true
          files: |
            dist/*
            tarballs/*
