name: Get Xcode Versions

on:
  workflow_dispatch:

jobs:
  get-versions:
    runs-on: macos-14
    outputs:
      xcode-versions: ${{ steps.get-versions.outputs.xcode-versions }}
    steps:
      - name: Checkout setup-xcode
        uses: actions/checkout@v4
        with:
          repository: maxim-lobanov/setup-xcode
          path: setup-xcode

      - name: Install setup-xcode dependencies
        working-directory: setup-xcode
        run: npm install
      - name: Create temporary file
        run: |
          cat << EOF > get_xcode_versions.ts
          import { XcodeSelector } from './xcode-selector';
          const selector = new XcodeSelector();
          const versions = await selector.getAllVersions();
          const formattedVersions = versions.map(v => v.stable ? v.version : v.version + '-beta');
          console.log('::set-output name=xcode-versions::' + JSON.stringify(formattedVersions));
          EOF

      - name: Get Xcode versions
        id: get-versions
        working-directory: setup-xcode/src
        run: |
          node get_xcode_versions.ts
